# Generated by Django 4.0.6 on 2022-10-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first__app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coin',
            field=models.IntegerField(default=1),
        ),
    ]
