# Generated by Django 4.0.6 on 2022-10-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first__app', '0004_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='user',
        ),
    ]
