# Generated by Django 4.0.6 on 2022-10-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first__app', '0005_rename_post_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
